modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT License"

[[mods]]
modId = "socketperms"
version = "${file.jarVersion}"
displayName = "SocketPerms"
#credits=""
authors = "The SocketMods Team"
description = '''
A proof-of-concept API and implementation for a new Forge permissions API.
'''

[[dependencies.socketperms]]
    modId = "forge"
    mandatory = true
    versionRange = "[36,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.socketperms]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.16.5,1.17)"
    ordering = "NONE"
    side = "BOTH"
